### ISSUE TITLE
如何加载其他embedding模型和rerank模型？

### ISSUE THREAD

**Issue by rookiexiao123** [netease-youdao/QAnything#105]
我知道了如何更换大模型，但是想知道如何更换embedding和rerank模型，请求帮助。

**Comment by songkq** [comment]
@rookiexiao123 Not supported yet. 
You can independently deploy a Embedding service and then integrate it into the QAnything system by calling the interface.
Refer to the source code `https://github.com/netease-youdao/QAnything/blob/master/qanything_kernel/connector/embedding/embedding_for_online.py` and `https://github.com/netease-youdao/QAnything/blob/208dc3ec64e627132f2e8bda3cb06ac5fcb3a602/qanything_kernel/core/local_doc_qa.py#L49`

**Comment by fredfany** [comment]
现在呢，是否已经支持了，或者说是否有这方面的计划

**Comment by MonkeyTB** [comment]
> 大

麻烦问下如何替换大模型的

**Comment by MonkeyTB** [comment]
> 我知道了如何更换大模型，但是想知道如何更换embedding和rerank模型，请求帮助。

麻烦问下如何替换大模型的，通过什么方式

**Comment by Leonardo123-ui** [comment]
把模型转成onnx格式的就可以，但是注意要更新Triton加载的config文件
