### ISSUE TITLE
Qwen-7B-QAnything能否提供4bit版本

### ISSUE THREAD

**Issue by bernardx** [netease-youdao/QAnything#126]
目前提供的8Bit版本无法被vllm加载，同时因为缺少pytorch_model.bin.index.json无法直接通过hf加载

**Comment by AprildreamMI** [comment]
所以运行`bash ./run.sh -c local -i 0 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything`，LLM服务无法启动？
![image](https://github.com/netease-youdao/QAnything/assets/31964372/31875410-5d90-4d36-aede-475ab17eba15)

**Comment by bernardx** [comment]
可以启动的，但hf推理效率较低，如果`bash ./run.sh -c local -i 0 -b vllm -m Qwen-7B-QAnything -t qwen-7b-qanything`  这样在一张24g的卡上显存是不够的，因为vllm不支持8bit。
所以希望手动转成4bit，但目前提供的版本无法转换。

**Comment by AprildreamMI** [comment]
> 可以启动的，但hf推理效率较低，如果`bash ./run.sh -c local -i 0 -b vllm -m Qwen-7B-QAnything -t qwen-7b-qanything` 这样在一张24g的卡上显存是不够的，因为vllm不支持8bit。 所以希望手动转成4bit，但目前提供的版本无法转换。

#127 我不清楚为什么我无法启动，前面的前后端服务启动一切正常，相应的模型文件也下载了
NVIDIA GeForce RTX 4060 Laptop GPU，1.8B，显存为 8188 MiB

**Comment by songkq** [comment]
@bernardx Update pytorch_model.bin.index.json
https://modelscope.cn/models/netease-youdao/Qwen-7B-QAnything/file/view/master/pytorch_model.bin.index.json?status=2

**Comment by t880216t** [comment]
> 感谢 已经可以正常加载量化

请问4bit模型在哪里获取的呢

**Comment by bernardx** [comment]
> > 感谢 已经可以正常加载量化
> 
> 请问4bit模型在哪里获取的呢

自己压缩下吧
