### ISSUE TITLE
[BUG] <title>Tesla V100-PCIE-16GB GPU 运行失败

### ISSUE THREAD

**Issue by lxshilaoda98** [netease-youdao/QAnything#128]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行命令：bash ./run.sh -c local -i 0 -b vllm -m Qwen-7B-QAnything -t qwen-7b-qanything
错误：
qanything-container-local  | LLM 服务正在启动，可能需要一段时间...你有时间去冲杯咖啡 :)
qanything-container-local  | 启动 LLM 服务超时，自动检查 /workspace/qanything_local/logs/debug_logs/fastchat_logs/fschat_model_worker_7801.log 中是否存在Error...
qanything-container-local  | 2024-02-20 21:46:23 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 795, in _run_workers
qanything-container-local  | 2024-02-20 21:46:23 | ERROR | stderr |     driver_worker_output = getattr(self.driver_worker,
qanything-container-local  | 2024-02-20 21:46:23 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 71, in init_model
qanything-container-local  | 2024-02-20 21:46:23 | ERROR | stderr |     _check_if_gpu_supports_dtype(self.model_config.dtype)
qanything-container-local  | 2024-02-20 21:46:23 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 231, in _check_if_gpu_supports_dtype
qanything-container-local  | 2024-02-20 21:46:23 | ERROR | stderr |     raise ValueError(
qanything-container-local  | 2024-02-20 21:46:23 | ERROR | stderr | ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-PCIE-16GB GPU has compute capability 7.0.

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04 
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-16GB           Off | 00000001:00:00.0 Off |                  Off |
| N/A   32C    P0              37W / 250W |   1636MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     44308      C   /opt/tritonserver/bin/tritonserver         1632MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by songkq** [comment]
@lxshilaoda98 Try to replace `--dtype bfloat16` with `--dtype float16` in run.sh

<img width="794" alt="image" src="https://github.com/netease-youdao/QAnything/assets/30183023/11220881-5ddd-4be4-9ad4-a5bf82c41f62">


https://github.com/netease-youdao/QAnything/blob/f435b125016bcbc7c22582aa730f54ce0d4a33df/scripts/run_for_local_option.sh#L199

**Comment by lxshilaoda98** [comment]
> @lxshilaoda98 Try to replace `--dtype bfloat16` with `--dtype float16` in run.sh尝试替换 `--dtype bfloat16` 为 `--dtype float16` in run.sh
> 
> <img alt="image" width="794" src="https://private-user-images.githubusercontent.com/30183023/307203157-11220881-5ddd-4be4-9ad4-a5bf82c41f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MjY4ODUsIm5iZiI6MTcwODkyNjU4NSwicGF0aCI6Ii8zMDE4MzAyMy8zMDcyMDMxNTctMTEyMjA4ODEtNWRkZC00YmU0LTlhZDQtYTViZjgyYzQxZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA1NDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MDg2YzJhNjlmZmUyZGYyMGRjOWIyNWZhZTAwYjczNTI2NGI0NjA4MzE4ZTg3ZmQzOGRjNTMwZjVkZWIwMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F59lnH5oBT0ZRnjnqHO6ZDUJJ6ovVZMPgsCF80sKC_Q">
> https://github.com/netease-youdao/QAnything/blob/f435b125016bcbc7c22582aa730f54ce0d4a33df/scripts/run_for_local_option.sh#L199

thanks!!!
