### ISSUE TITLE
[BUG] Failed to build the front end.

### ISSUE THREAD

**Issue by huweibin1983** [netease-youdao/QAnything#129]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

dhaims@DHAIMS:/mnt/e/QAnything/public/QAnythingDev$ bash ./run.sh -c local -i 0 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything
error: RPC failed; curl 16 Error in the HTTP2 framing layer
fatal: expected flush after ref listing
当前master分支已是最新，无需更新。
请输入您使用的大模型B数(示例：1.8B/3B/7B): 7B
model_size=7B
GPUID1=0, GPUID2=0, device_id=0
GPU1 Model: NVIDIA GeForce RTX 3090
Compute Capability: 8.6
OCR_USE_GPU=True because 8.6 >= 7.5
====================================================
******************** 重要提示 ********************
====================================================

您当前的显存为 24576 MiB 推荐部署7B模型
llm_api is set to [local]
device_id is set to [0]
runtime_backend is set to [hf]
model_name is set to [Qwen-7B-QAnything]
conv_template is set to [qwen-7b-qanything]
tensor_parallel is set to [1]
gpu_memory_utilization is set to [0.81]
models 文件夹已存在，无需下载。
检查模型版本成功，当前版本为 v2.1.0。
Model directories check passed. (0/8)
模型路径和模型版本检查通过. (0/8)
Do you want to use the previous host: localhost? (yes/no) 是否使用上次的host: localhost？(yes/no) 回车默认选yes，请输入:yes
Running under WSL
 Container qanything-container-local  Stopping
 Container qanything-container-local  Stopped
 Container qanything-container-local  Removing
 Container qanything-container-local  Removed
 Container mysql-container-local  Stopping
 Container milvus-standalone-local  Stopping
 Container milvus-standalone-local  Stopped
 Container milvus-standalone-local  Removing
 Container milvus-standalone-local  Removed
 Container milvus-minio-local  Stopping
 Container milvus-etcd-local  Stopping
 Container milvus-etcd-local  Stopped
 Container milvus-etcd-local  Removing
 Container milvus-etcd-local  Removed
 Container mysql-container-local  Stopped
 Container mysql-container-local  Removing
 Container mysql-container-local  Removed
 Container milvus-minio-local  Stopped
 Container milvus-minio-local  Removing
 Container milvus-minio-local  Removed
 Network qanything_milvus_mysql_local  Removing
 Network qanything_milvus_mysql_local  Removed
[+] Running 6/6
 ✔ Network qanything_milvus_mysql_local  Created                                                                   0.1s
 ✔ Container mysql-container-local       Started                                                                   0.7s
 ✔ Container milvus-etcd-local           Started                                                                   0.7s
 ✔ Container milvus-minio-local          Started                                                                   0.7s
 ✔ Container milvus-standalone-local     Started                                                                   0.1s
 ✔ Container qanything-container-local   Started                                                                   0.1s
qanything-container-local  |
qanything-container-local  | =============================
qanything-container-local  | == Triton Inference Server ==
qanything-container-local  | =============================
qanything-container-local  |
qanything-container-local  | NVIDIA Release 23.05 (build 61161506)
qanything-container-local  | Triton Server Version 2.34.0
qanything-container-local  |
qanything-container-local  | Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local  |
qanything-container-local  | Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local  |
qanything-container-local  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
qanything-container-local  | By pulling and using the container, you accept the terms and conditions of this license:
qanything-container-local  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
qanything-container-local  |
qanything-container-local  | llm_api is set to [local]
qanything-container-local  | device_id is set to [0]
qanything-container-local  | runtime_backend is set to [hf]
qanything-container-local  | model_name is set to [Qwen-7B-QAnything]
qanything-container-local  | conv_template is set to [qwen-7b-qanything]
qanything-container-local  | tensor_parallel is set to [1]
qanything-container-local  | gpu_memory_utilization is set to [0.81]
qanything-container-local  | checksum d2b4b76c6bee2ea6bf238481dfc76c05
qanything-container-local  | default_checksum d2b4b76c6bee2ea6bf238481dfc76c05
qanything-container-local  |
qanything-container-local  | [notice] A new release of pip is available: 23.3.2 -> 24.0
qanything-container-local  | [notice] To update, run: python3 -m pip install --upgrade pip
qanything-container-local  | GPU ID: 0, 0
qanything-container-local  | The triton server for embedding and reranker will start on 0 GPUs
qanything-container-local  | Executing hf runtime_backend
qanything-container-local  | The rerank service is ready! (2/8)
qanything-container-local  | rerank服务已就绪! (2/8)
qanything-container-local  | The ocr service is ready! (3/8)
qanything-container-local  | OCR服务已就绪! (3/8)
qanything-container-local  | The qanything backend service is ready! (4/8)
qanything-container-local  | qanything后端服务已就绪! (4/8)
qanything-container-local  | Waiting for [npm run install]（5/8)

qanything-container-local  | added 3 packages in 3s
qanything-container-local  |
qanything-container-local  | 179 packages are looking for funding
qanything-container-local  |   run `npm fund` for details
qanything-container-local  | npm notice
qanything-container-local  | npm notice New minor version of npm available! 10.2.3 -> 10.4.0
qanything-container-local  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.4.0
qanything-container-local  | npm notice Run npm install -g npm@10.4.0 to update!
qanything-container-local  | npm notice
qanything-container-local  | [npm run install] Installed successfully（5/8)
qanything-container-local  | Waiting for [npm run build](6/8)
qanything-container-local  |
qanything-container-local  | > ai-demo@1.0.1 build
qanything-container-local  | > vite build
qanything-container-local  |
qanything-container-local  | The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
qanything-container-local  | vite v5.1.3 building for production...

qanything-container-local  | ~@/styles/fonts/FZLanTingHeiS-L-GB.TTF referenced in /workspace/qanything_local/front_end/src/styles/common/global.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime
qanything-container-local  |
qanything-container-local  | ~@/styles/fonts/FZYaSongS-B-GB.TTF referenced in /workspace/qanything_local/front_end/src/styles/common/global.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime
[plugin:vite-plugin-eslint]
qanything-container-local  | /workspace/qanything_local/front_end/src/components/Defaultpage.vue
qanything-container-local  |   51:3  warning  Unexpected console statement  no-console
qanything-container-local  |
qanything-container-local  | ✖ 1 problem (0 errors, 1 warning)
qanything-container-local  |
[plugin:vite-plugin-eslint]
qanything-container-local  | /workspace/qanything_local/front_end/src/components/Chat.vue
qanything-container-local  |   271:7   warning  Unexpected console statement  no-console
qanything-container-local  |   273:9   warning  Unexpected console statement  no-console
qanything-container-local  |   286:13  warning  Unexpected console statement  no-console
qanything-container-local  |   292:7   warning  Unexpected console statement  no-console
qanything-container-local  |   294:7   warning  Unexpected console statement  no-console
qanything-container-local  |   310:7   warning  Unexpected console statement  no-console
qanything-container-local  |   311:7   warning  Unexpected console statement  no-console
qanything-container-local  |   321:7   warning  Unexpected console statement  no-console
qanything-container-local  |   336:3   warning  Unexpected console statement  no-console
qanything-container-local  |   367:5   warning  Unexpected console statement  no-console
qanything-container-local  |   387:7   warning  Unexpected console statement  no-console
qanything-container-local  |   391:5   warning  Unexpected console statement  no-console
qanything-container-local  |
qanything-container-local  | ✖ 12 problems (0 errors, 12 warnings)
qanything-container-local  |
[plugin:vite-plugin-eslint]
qanything-container-local  | /workspace/qanything_local/front_end/src/components/Head.vue
qanything-container-local  |   65:3  warning  Unexpected console statement  no-console
qanything-container-local  |
qanything-container-local  | ✖ 1 problem (0 errors, 1 warning)
qanything-container-local  |
[plugin:vite-plugin-eslint]
qanything-container-local  | /workspace/qanything_local/front_end/src/components/OptionList.vue
qanything-container-local  |   196:5  warning  Unexpected console statement  no-console
qanything-container-local  |   206:3  warning  Unexpected console statement  no-console
qanything-container-local  |
qanything-container-local  | ✖ 2 problems (0 errors, 2 warnings)
qanything-container-local  |
Failed to build the front end.

### 运行环境 | Environment

```Markdown
- OS:Windows 11 WSL2
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

**Comment by merliniyang** [comment]
构建前端超时，默认设置的是180s。修改/QAnything/scripts里面的run_for_local_option.sh文件。
我的sh文件修改成1800秒了，供参考。注意：如果在windows环境修改.sh文件后，请用dos2unix转换一下格式。

# 构建前端项目
echo "Waiting for [npm run build](6/8)"
**timeout 1800** npm run build
if [ $? -eq 0 ]; then
    echo "[npm run build] build successfully(6/8)"
elif [ $? -eq 124 ]; then
    echo "npm run build **编译超时(1800秒)**，请查看上面的输出。"
    exit 1
else
    echo "Failed to build the front end."

**Comment by huweibin1983** [comment]
> 构建前端超时，默认设置的是180s。修改/QAnything/scripts里面的run_for_local_option.sh文件。 我的sh文件修改成1800秒了，供参考。注意：如果在windows环境修改.sh文件后，请用dos2unix转换一下格式。
> 
> # 构建前端项目
> echo "Waiting for [npm run build](6/8)" **timeout 1800** npm run build if [ $? -eq 0 ]; then echo "[npm run build] build successfully(6/8)" elif [ $? -eq 124 ]; then echo "npm run build **编译超时(1800秒)**，请查看上面的输出。" exit 1 else echo "Failed to build the front end."

按照您的设置，成功运行，谢谢！
