### ISSUE TITLE
如何配置接入Qwen的 llm-api

### ISSUE THREAD

**Issue by warrenwangxd** [netease-youdao/QAnything#132]
接入openai 的api成本较高，国内阿里云的Qwen-api价格较低，且效果也还OK,该如何接入呢？

**Comment by songkq** [comment]
Try to implement a similar LLM interface to replace the OpenAILLM
https://github.com/netease-youdao/QAnything/blob/f435b125016bcbc7c22582aa730f54ce0d4a33df/qanything_kernel/connector/llm/llm_for_openai_api.py#L27

**Comment by ssbg2** [comment]
> 接入openai 的api成本较高，国内阿里云的Qwen-api价格较低，且效果也还OK,该如何接入呢？

您好，您这部分有继续尝试么？
