### ISSUE TITLE
[BUG] 切换到vllm后端，或者hf后端, 启动报： _pickle.UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by xiaobin-zhang** [netease-youdao/QAnything#155]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用QANYTHING-1.2.0版本，启动使用 -c local -b default 时，报Triton Inference Error (error_code: 4)， 然后使用 -b hf 或 -b vllm 启动，报：_pickle.UnpicklingError: invalid load key, 'v'

### 期望行为 | Expected Behavior

期望可以使用hf 或 vllm 能启动成功

### 运行环境 | Environment

```Markdown
- OS: 麒麟 V10
- NVIDIA Driver: 535.154.05
- CUDA: 12.2
- docker: 19.03.15
- docker-compose: 使用的k8s部署
- NVIDIA GPU: A800
- NVIDIA GPU Memory: 80G
```

### QAnything日志 | QAnything logs

![9a752d0aad863d47c90eff06eedd255](https://github.com/netease-youdao/QAnything/assets/19240244/8009cc4c-9e44-4372-af4f-93d206913a24)

### 复现方法 | Steps To Reproduce

1. 进入qanything容器 执行： /workspace/qanything_local/scripts/run_for_local_option.sh -c local -i 1 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything -p 1 -r 0.81
2. 查看 fschat_model_worker_7801.log

**Comment by waht-X** [comment]
> @chenyangchi 我仔细检查了一下assets\custom_models\Qwen-7B-QAnything 包下的模型文件，发现是文件缺失了，没有下载完整。重新下载就好了。 ![1ed878b011a3f2dfbac5d414688b166](https://private-user-images.githubusercontent.com/19240244/310919840-98849275-00e8-4a8e-a8d1-c959c621e45f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Mzc1NDMsIm5iZiI6MTcxMTQzNzI0MywicGF0aCI6Ii8xOTI0MDI0NC8zMTA5MTk4NDAtOTg4NDkyNzUtMDBlOC00YThlLWE4ZDEtYzk1OWM2MjFlNDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA3MTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMTk3ZmRjMzBjN2EwZmY3YTVjYmQzY2ZkODVjMTAzMjJiNzlkZmVkYjQ2NmZiOTlkNjJkMGYzMzJlOTAwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zXnA-S4CQe8swcMphTgTCSaW_hWxBJ7jMnp2DFjLK28) 请注意上图的这两个文件大小，检查你下载的文件大小是不远没有这么大

我想问下为什么会没有下载完呢，我也遇到了这个问题，但是我重复下载多次这个文件也是一样的，只有这两个大文件是只下载了几kb但是git显示已全部下载完成，并且我这网络还是很好的（公司网络），最后只能是手动下载解决

**Comment by xiaolinfrank** [comment]
> > @chenyangchi 我仔细检查了一下assets\custom_models\Qwen-7B-QAnything 包下的模型文件，发现是文件缺失了，没有下载完整。重新下载就好了。 ![1ed878b011a3f2dfbac5d414688b166](https://private-user-images.githubusercontent.com/19240244/310919840-98849275-00e8-4a8e-a8d1-c959c621e45f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Mzc1NDMsIm5iZiI6MTcxMTQzNzI0MywicGF0aCI6Ii8xOTI0MDI0NC8zMTA5MTk4NDAtOTg4NDkyNzUtMDBlOC00YThlLWE4ZDEtYzk1OWM2MjFlNDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA3MTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMTk3ZmRjMzBjN2EwZmY3YTVjYmQzY2ZkODVjMTAzMjJiNzlkZmVkYjQ2NmZiOTlkNjJkMGYzMzJlOTAwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zXnA-S4CQe8swcMphTgTCSaW_hWxBJ7jMnp2DFjLK28) 请注意上图的这两个文件大小，检查你下载的文件大小是不远没有这么大
> 
> 我想问下为什么会没有下载完呢，我也遇到了这个问题，但是我重复下载多次这个文件也是一样的（我是直接使用git clone下载，没有使用lfs），只有这两个大文件是只下载了几kb但是git显示已全部下载完成，并且我这网络还是很好的（公司网络），最后只能是手动下载解决

请先安装 [git lfs](https://github.com/netease-youdao/QAnything/blob/master/docs/docker%E7%89%88%E6%9C%AC%E5%AE%89%E8%A3%85%E6%94%BB%E7%95%A5.md#%E5%AE%89%E8%A3%85-git-lfs)，然后重新 clone 即可
