### ISSUE TITLE
[BUG] 是否不支持文献文件的识别？报错split或embedding失败，请检查文件类型

### ISSUE THREAD

**Issue by honins** [netease-youdao/QAnything#160]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我上传了一篇pdf类型的文献
内容格式如下：
![截图 2024-03-08 10-10-49](https://github.com/netease-youdao/QAnything/assets/23189048/78b1531b-7a3c-40f7-b559-fa2c45cec7ef)

文档解析失败，返回的备注为：
```
split或embedding失败，请检查文件类型，仅支持[md,txt,pdf,jpg,png,jpeg,docx,xlsx,pptx,eml,csv]
```

看起来是分词失败，是否不支持这个这种上下结构的文献识别？

### 期望行为 | Expected Behavior

支持文献类型的识别和问答

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04 
- NVIDIA Driver:525.105.17
- CUDA:Cuda compilation tools, release 12.1, V12.1.105
- docker: 25.03
- docker-compose: 24.0.5
- NVIDIA GPU:GTX 4080 Super
- NVIDIA GPU Memory:16GB
```

### 复现方法 | Steps To Reproduce
将文献上传知识库即可复现
_No response_

**Comment by shu1ao2han3** [comment]
同有这个问题，普通的txt上传知识库也会报错解析失败。

**Comment by honins** [comment]
> 同有这个问题，普通的txt上传知识库也会报错解析失败。

我重启后好了，翻了下日志，应该是显存不够导致的

**Comment by shu1ao2han3** [comment]
> > 同有这个问题，普通的txt上传知识库也会报错解析失败。
> 
> 我重启后好了，翻了下日志，应该是显存不够导致的

因为公司用的是虚拟机，不是物理机，所以没有显卡。
我之前用的langchain-chatchat，在走到embedding这步。用纯CPU，也可以实现。但是这个qanything默认配置就不可以。
想问下楼主，在程序中有找到相关的配置吗。

**Comment by honins** [comment]
> > > 同有这个问题，普通的txt上传知识库也会报错解析失败。
> > 
> > 
> > 我重启后好了，翻了下日志，应该是显存不够导致的
> 
> 因为公司用的是虚拟机，不是物理机，所以没有显卡。 我之前用的langchain-chatchat，在走到embedding这步。用纯CPU，也可以实现。但是这个qanything默认配置就不可以。 想问下楼主，在程序中有找到相关的配置吗。

readme中有更改模型的配置 https://github.com/netease-youdao/QAnything/blob/master/docs/QAnything_Startup_Usage_README.md

**Comment by shu1ao2han3** [comment]
> > > > 同有这个问题，普通的txt上传知识库也会报错解析失败。
> > > 
> > > 
> > > 我重启后好了，翻了下日志，应该是显存不够导致的
> > 
> > 
> > 因为公司用的是虚拟机，不是物理机，所以没有显卡。 我之前用的langchain-chatchat，在走到embedding这步。用纯CPU，也可以实现。但是这个qanything默认配置就不可以。 想问下楼主，在程序中有找到相关的配置吗。
> 
> readme中有更改模型的配置 https://github.com/netease-youdao/QAnything/blob/master/docs/QAnything_Startup_Usage_README.md

好的，蟹蟹楼主。
