### ISSUE TITLE
源码启动

### ISSUE THREAD

**Issue by hehuang139** [netease-youdao/QAnything#173]
是否有源码启动的说明，用于修改调试？

**Comment by hehuang139** [comment]
现在服务有报错，但是问issue没有回应，是否可以告诉源码调试方式，我们也可以帮忙处理？

**Comment by hehuang139** [comment]
这个项目是否有维护，官方能说下吗？

**Comment by Ma-Dan** [comment]
https://github.com/Ma-Dan/QAnything/blob/cpu/%E6%9C%AC%E5%9C%B0CPU%E9%83%A8%E7%BD%B2%E5%92%8C%E8%B0%83%E8%AF%95%E6%96%B9%E6%B3%95.txt
试试这个，milvus和mysql还是docker运行，3个模型和前后端服务都在本地，可以源码调试

**Comment by hehuang139** [comment]
Ok,感谢反馈
