### ISSUE TITLE
[BUG] 上传文档后文档状态一直是“解析中”

### ISSUE THREAD

**Issue by honins** [netease-youdao/QAnything#174]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

上传文档后文档状态一直是“解析中”
![Screenshot 2024-03-14 at 17-08-19 QAnything](https://github.com/netease-youdao/QAnything/assets/23189048/772de8de-adce-4876-b0a9-94058b7c4280)

ocr_server.log和llm_embed_rerank_tritonserver.log文件中一直也没有报错。
这是什么原因？

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04 
- NVIDIA Driver:525.105.17
- CUDA:Cuda compilation tools, release 12.1, V12.1.105
- docker: 25.03
- docker-compose: 24.0.5
- NVIDIA GPU:GTX 4080 Super
- NVIDIA GPU Memory:16GB
```

**Comment by fivegg** [comment]
我也是。终端有显示：qanything-container-local  | Embedding and Rerank 服务正在启动，可能需要一段时间...你有时间去冲杯咖啡 :)
qanything-container-local  | 启动 embedding and rerank 服务超时，自动检查 /workspace/qanything_local/logs/debug_logs/embed_rerank_tritonserver.log 中是否存在Error...
qanything-container-local  | /workspace/qanything_local/logs/debug_logs/embed_rerank_tritonserver.log 中未检测到明确的错误信息。请手动排查 /workspace/qanything_local/logs/debug_logs/embed_rerank_tritonserver.log 以获取更多信息。但是查看log未见异常

**Comment by honins** [comment]
> 我也是。终端有显示：qanything-container-local | Embedding and Rerank 服务正在启动，可能需要一段时间...你有时间去冲杯咖啡 :) qanything-container-local | 启动 embedding and rerank 服务超时，自动检查 /workspace/qanything_local/logs/debug_logs/embed_rerank_tritonserver.log 中是否存在Error... qanything-container-local | /workspace/qanything_local/logs/debug_logs/embed_rerank_tritonserver.log 中未检测到明确的错误信息。请手动排查 /workspace/qanything_local/logs/debug_logs/embed_rerank_tritonserver.log 以获取更多信息。但是查看log未见异常

我排查下来，应该还是电脑配置问题，显存不够用了
