### ISSUE TITLE
Support NV RTX A5000

### ISSUE THREAD

**Issue by SUGE2016** [netease-youdao/QAnything#180]
**Please Describe The Problem To Be Solved**
NV RTX A5000 Not supported, Not know why
Any plan to support it? or Why not, some necessary features A5000 not have?

**Comment by wildish** [comment]
To support A5000
1. modify`./scripts/gpu_capabilities.json`, add `NVIDIA RTX A5000": 8.6,`;
2. modify`./scripts/run_for_local_option.sh`, line 152`gpu_series=$(echo $gpu_model | grep -oP '(RTX\s*(30|40)|A(10|30|40|100|800))')` to `gpu_series=$(echo $gpu_model | grep -oP '(RTX\s*(30|40)|A(10|30|40|100|800|5000))')`
then run

**Comment by SUGE2016** [comment]
Worked!
