### ISSUE TITLE
支持更多的7B大模型

### ISSUE THREAD

**Issue by fifiand1** [netease-youdao/QAnything#186]
在单显卡<=16G显存，例如4080上，7B模型是否是最优解？

希望能增加支持Llama、Gemma的7B模型

**Comment by deutschthomas** [comment]
可以尝试用ollama等提供openAI API的本地LLM包装器实现

**Comment by cakat** [comment]
> 可以尝试用ollama等提供openAI API的本地LLM包装器实现

这个是否能跑通，还望赐教，我用 ollama  和  LLM  都没有跑通

**Comment by vc5409ftu** [comment]
7B得24G
