### ISSUE TITLE
[BUG] ERROR: Cannot install -r requirements.txt, because of protobuf version conflicting 

### ISSUE THREAD

**Issue by ALLinLLM** [netease-youdao/QAnything#187]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I'm installing using pip:
`pip install -r requirements.txt`

ERROR: Cannot install -r requirements.txt (line 13), -r requirements.txt (line 16), -r requirements.txt (line 19), -r requirements.txt (line 20) and tritonclient[all]==2.31.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    pymilvus 2.3.4 depends on protobuf>=3.20.0
    paddlepaddle-gpu 2.5.2 depends on protobuf>=3.20.2; platform_system != "Windows"
    mysql-connector-python 8.2.0 depends on protobuf<=4.21.12 and >=4.21.1
    onnxruntime-gpu 1.16.3 depends on protobuf
    tritonclient[all] 2.31.0 depends on protobuf<4 and >=3.5.0; extra == "all"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### 期望行为 | Expected Behavior

the cmd `pip install -r requirements.txt` can be successfully executed

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04.6 LTS
- NVIDIA Driver:530.41.03
- CUDA: V12.1.66
- docker: 24.0.6
- docker-compose:1.25.0
- NVIDIA GPU:RTX 4090
- NVIDIA GPU Memory: 24GB
```

### QAnything日志 | QAnything logs

无日志

### 复现方法 | Steps To Reproduce

1. `git clone git@github.com:netease-youdao/QAnything.git`
2. `cd QAnything`
3. `git log`
```
commit d5c59260a1af74f01a9b378b567435ab0caa40df (HEAD -> master, origin/master, origin/HEAD)
Author: xixihahaliu <xixihahaliu01@gmail.com>
Date:   Tue Mar 19 21:00:49 2024 +0800

    fix: Partial model matching error in computing power.

commit e75a0c8a98df7857390d94d68892bc1b0dc762de
Author: successren <fieeldren@gmail.com>
Date:   Tue Mar 19 13:43:33 2024 +0800

    update wechat QR code image
...
```
5. `pip install -r requirements.txt`

**Comment by ALLinLLM** [comment]
repeat with #90

**Comment by cjw-d** [comment]
我也遇到了同样的问题,请问你解决了吗

**Comment by ALLinLLM** [comment]
@cjw-d the official reply in #90 recommend to use docker, just `bash run.sh` and docker container will startup and the webui can be opened.

**Comment by zainzhoucom** [comment]
pip install -r requirements.txt --no-deps
