### ISSUE TITLE
[issue] milvus_client.py的向量库计算相似度（metric_type）的时候为什么选L2？

### ISSUE THREAD

**Issue by 62bit** [netease-youdao/QAnything#218]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我看到milvus_client.py中的metric_type选了L2，但是我查了一下各种资料，感觉COSINE可能更合适，想请教一下作者是怎么考虑的。
```
self.search_params = {"metric_type": "L2", "params": {"nprobe": 256}}
```

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- docker:
- docker-compose:
- NVIDIA GPU:
- NVIDIA GPU Memory:
```

**Comment by 62bit** [comment]
是因为归一化吗

**Comment by successren** [comment]
Yes, our embeddings are normalized, so L2 and cosine distances are equivalent.
