### ISSUE TITLE
QAnything RoadMap Suggestions

### ISSUE THREAD

**Issue by successren** [netease-youdao/QAnything#224]
Feel free to share any comments or suggestions for QAnything here. Whether you have ideas for new features or improvements.
Let's collaborate to plan the future of QAnything together!
Please like the corresponding comment to show your support for the suggestion.

对QAnything的未来有什么意见或者建议，希望增加什么新的功能，都可以集中在这里提！
我们共同规划QAnything的未来！
请在对应评论下面点赞来表示你支持该建议。

Adopted suggestions|已采纳的建议：

- [ ] [希望增加对应图片输出的功能](https://github.com/netease-youdao/QAnything/issues/224#issuecomment-2042203868) @changqingla

**Comment by xiaoma1990-git** [comment]
问下 现在3B的模型 除了MiniChat-2-3B 还有其他的吗 目前这个启动不完全正确 不知道怎么解决

**Comment by changqingla** [comment]
希望增加对应图片输出的功能

**Comment by MonkeyTB** [comment]
qanything-container-local  | 您的显卡型号 NVIDIA H100 PCIe 不在支持列表中，请联系技术支持。
是不是需要支持更多的显卡？不确定是我使用的问题还是其他

**Comment by YQisme** [comment]
希望支持网页的路径或者子目录，而不是单个网页

**Comment by ILG2021** [comment]
排版上有点小建议，回复的答案和摘自的内容可以在字体颜色或者大小上区分下，更加有层次。
另外很希望bce能支持微调。
不知道ui上能否区分管理员模式和普通用户模式，我希望普通用户无法对资料进行管理，只有对话界面。

**Comment by successren** [comment]
Please move the discussion to https://qanything.canny.io/. Also, I have transfer the feedback from this page to the web.
