### ISSUE TITLE
[ISSUE] <启动后端服务超时，无法连接至mysql服务>

### ISSUE THREAD

**Issue by kkkkkkkkkka** [netease-youdao/QAnything#238]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行命令：bash ./run.sh -i 1
终端报错如下：启动后端服务超时，请检查日志文件 /workspace/qanything_local/logs/debug_logs/sanic_api.log 获取更多信息。
日志显示错误如下：
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql-container-local:3306' (111)
[2024-04-09 21:37:51 +0800] [207] [ERROR] Not all workers acknowledged a successful startup. Shutting down.
尝试过按照FAQ_zh提供的方法，将volumes删除后重新启动，但还是不行。

### 期望行为 | Expected Behavior

成功启动后端服务

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- docker:
- docker-compose:
- NVIDIA GPU:
- NVIDIA GPU Memory:
```

**Comment by flexer2018** [comment]
修改docker 的配置文件。
  
mysql:
    container_name: mysql-container-local
    privileged: true
    image: mysql
    #     ports:
    #       - "3306:3306"
    command: --max-connections=10000
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/mysql:/var/lib/mysql
改一下这里，改成100还不够，我直接加到10000才行
    command: --max-connections=10000

**Comment by epicblue** [comment]
我也碰到了这个问题补充一下：

运行环境 | Environment
- OS:Win11 23H2
- NVIDIA Driver:
- CUDA:
- docker: 25.0.3
- docker-compose: v2.24.6-desktop.1
- NVIDIA GPU: 4060 Ti
- NVIDIA GPU Memory: 16G

**Comment by xixihahaliu** [comment]
@epicblue @kkkkkkkkkka  此问题已修复，重新拉取代码即可，mysql最大连接数已设为1000，可手动修改：volumes/mysql.conf

**Comment by Halfknow** [comment]
> @epicblue @kkkkkkkkkka 此问题已修复，重新拉取代码即可，mysql最大连接数已设为1000，可手动修改：volumes/mysql.conf

似乎还是没有解决这个问题，不管linux还是wsl拉取了5.13最新的master代码之后，两边都出现了mysql connections 连接数超过的问题，其中wsl通过 docker compose yml 配置文件中添加 command: --max-connections=10000 这行代码解决了 mysql 问题。
