### ISSUE TITLE
在线体验不行，直接报错[BUG] <title>

### ISSUE THREAD

**Issue by qwexr** [netease-youdao/QAnything#24]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

**Comment by xixihahaliu** [comment]
麻烦提供一下详细的报错信息，也可以加一下微信群回复更及时

**Comment by successren** [comment]
Service was suspended yesterday morning. You can try again
