### ISSUE TITLE
云端启动为什么会有2个不存在的whl文件

### ISSUE THREAD

**Issue by liweiyang2023** [netease-youdao/QAnything#249]
# pip install third_party/es/whl/elastic_transport-8.12.0-py3-none-any.whl
 # pip install third_party/es/whl/elasticsearch-8.12.1-py3-none-any.whl
我看仓库里也不存在这2个,我运行时提示找不到这2个文件而产生报错

**Comment by solin666** [comment]
elastic_transport-8.12.0-py3-none-any.whl
从https://pypi.tuna.tsinghua.edu.cn/simple/elastic-transport/ 下载

elasticsearch-8.12.1-py3-none-any.whl
从https://pypi.tuna.tsinghua.edu.cn/simple/elasticsearch/ 下载

两个文件下载下来后，放到  /QAnything-master/third_party/es/whl下 （whl文件夹要自己创建），
重启启动，不再报错！

**Comment by xixihahaliu** [comment]
这两个whl在最新版代码中已删除，因为在freeren/qanything(-win):v1.2.2版本镜像中已经安装了这俩whl，请查看使用的镜像版本是否是最新的，对应的代码：https://github.com/netease-youdao/QAnything/blob/master/docker-compose-linux.yaml#L104 或 https://github.com/netease-youdao/QAnything/blob/master/docker-compose-windows.yaml#L103

**Comment by liweiyang2023** [comment]
> 这两个whl在最新版代码中已删除，因为在freeren/qanything(-win):v1.2.2版本镜像中已经安装了这俩whl，请查看使用的镜像版本是否是最新的，对应的代码：https://github.com/netease-youdao/QAnything/blob/master/docker-compose-linux.yaml#L104 或 https://github.com/netease-youdao/QAnything/blob/master/docker-compose-windows.yaml#L103

感谢,我自己已经手动解决了,thanks
