### ISSUE TITLE
在linux上部署，docker compose出错

### ISSUE THREAD

**Issue by chiiscoming** [netease-youdao/QAnything#26]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

command：sudo docker-compose -f docker-compose-linux.yaml up qanything_local

ERROR: The Compose file './docker-compose-linux.yaml' is invalid because:
services.qanything_local.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)

ps：I pull latest code and changed nothing.

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

**Comment by chiiscoming** [comment]
issue solved. The previous vision of docker compose is too old. Just update the docker compose.

**Comment by ybdesire** [comment]
> issue solved. The previous vision of docker compose is too old. Just update the docker compose.

Would you help share which version works?
