### ISSUE TITLE
docker启动失败

### ISSUE THREAD

**Issue by Hughhuh** [netease-youdao/QAnything#27]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:545.23.06
- CUDA:12.3
- Docker Compose:2.18.1
- NVIDIA GPU Memory:24G
```

### QAnything日志 | QAnything logs

qanything-container-local  | 
qanything-container-local  | =============================
qanything-container-local  | == Triton Inference Server ==
qanything-container-local  | =============================
qanything-container-local  | 
qanything-container-local  | NVIDIA Release 23.05 (build 61161506)
qanything-container-local  | Triton Server Version 2.34.0
qanything-container-local  | 
qanything-container-local  | Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local  | 
qanything-container-local  | Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local  | 
qanything-container-local  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
qanything-container-local  | By pulling and using the container, you accept the terms and conditions of this license:
qanything-container-local  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
qanything-container-local  | 
qanything-container-local  | /opt/nvidia/nvidia_entrypoint.sh: line 49: /workspace/qanything_local/scripts/run_for_local.sh: Permission denied
qanything-container-local  | /opt/nvidia/nvidia_entrypoint.sh: line 49: exec: /workspace/qanything_local/scripts/run_for_local.sh: cannot execute: Permission denied
qanything-container-local exited with code 126

### 复现方法 | Steps To Reproduce

docker compose -f docker-compose-linux.yaml up qanything_local

**Comment by songkq** [comment]
@Hughhuh 试试 chmod +wx .scripts/run_for_local.sh，再启动

**Comment by Hughhuh** [comment]
qanything-container-local  | 
qanything-container-local  | =============================
qanything-container-local  | == Triton Inference Server ==
qanything-container-local  | =============================
qanything-container-local  | 
qanything-container-local  | NVIDIA Release 23.05 (build 61161506)
qanything-container-local  | Triton Server Version 2.34.0
qanything-container-local  | 
qanything-container-local  | Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local  | 
qanything-container-local  | Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local  | 
qanything-container-local  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
qanything-container-local  | By pulling and using the container, you accept the terms and conditions of this license:
qanything-container-local  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
qanything-container-local  | 
qanything-container-local  | /opt/nvidia/nvidia_entrypoint.sh: line 49: exec: -h: invalid option
qanything-container-local  | exec: usage: exec [-cl] [-a name] [command [argument ...]] [redirection ...]
qanything-container-local exited with code 2
现在这个报错

**Comment by Hughhuh** [comment]
重新下一下脚本好了，此贴终结
