### ISSUE TITLE
支持MAC系统吗

### ISSUE THREAD

**Issue by loveyanzhongli** [netease-youdao/QAnything#30]
版本 14.2.1
图形卡 Intel UHD Graphics 630 1536 MB

运行 docker-compose -f docker-compose-linux.yaml up qanything_local

报错：
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

**Comment by songkq** [comment]
@loveyanzhongli  目前需要Nvidia卡，暂不支持Mac。后续有计划支持Mac纯离线版本。

**Comment by loveyanzhongli** [comment]
嗯好的，谢谢
