### ISSUE TITLE
cv2.imread(filename) 对应的 java 方法

### ISSUE THREAD

**Issue by shguan2018** [netease-youdao/QAnything#370]
这段代码,如果用 java代码怎么书写?  谢谢
![Snipaste_2024-05-29_18-06-29](https://github.com/netease-youdao/QAnything/assets/45221801/f4e1eb85-73e5-411d-bf80-de31fc75c35e)

**Comment by shguan2018** [comment]
这段代码 在  qanything_kernel\utils\loader\image_loader.py 中

**Comment by shguan2018** [comment]
已经找到了相应的 java 方法

**Comment by halahw** [comment]
> 已经找到了相应的 java 方法

大佬，方便分享一下吗？

**Comment by shguan2018** [comment]
![QQ图片20240820172202](https://github.com/user-attachments/assets/503934d7-b506-4988-9c13-e1d6c9579ac1)
