### ISSUE TITLE
[BUG] <前端最多传3轮历史对话吗，超过三轮对话就清空历史了>

### ISSUE THREAD

**Issue by chong-w** [netease-youdao/QAnything#373]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

前端请求后端local_doc_chat接口时，第四轮对话会把前三轮的history清空，传了个空的history给后端，我在model_config.py里面配置了LLM_HISTORY_LEN也不起作用。

### 期望行为 | Expected Behavior

希望前端放开传历史对话轮数的限制

### 复现方法 | Steps To Reproduce

1. 浏览器打开前端，F12打开调试
2. 开启多轮对话按钮
3. 进行三轮对话
4. 提第四个问题，可以看到http请求history=[]

**Comment by knightwj** [comment]
同样的问题

**Comment by dblab0** [comment]
这是docker版本的还是python版本的？

**Comment by chong-w** [comment]
> 这是docker版本的还是python版本的？
python

**Comment by chong-w** [comment]
大伙们可以看看1.3.0版本，那个前端有开源，可以自己改。

**Comment by xinxin12345** [comment]
> ### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
> * [x]  我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions
> 
> ### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?
> * [x]  我已经搜索过FAQ | I have searched FAQ
> 
> ### 当前行为 | Current Behavior
> 前端请求后端local_doc_chat接口时，第四轮对话会把前三轮的history清空，传了个空的history给后端，我在model_config.py里面配置了LLM_HISTORY_LEN也不起作用。
> 
> ### 期望行为 | Expected Behavior
> 希望前端放开传历史对话轮数的限制
> 
> ### 运行环境 | Environment
> _No response_
> 
> ### QAnything日志 | QAnything logs
> _No response_
> 
> ### 复现方法 | Steps To Reproduce
> 1. 浏览器打开前端，F12打开调试
> 2. 开启多轮对话按钮
> 3. 进行三轮对话
> 4. 提第四个问题，可以看到http请求history=[]
> 
> ### 备注 | Anything else?
> _No response_

请问如何开启多轮对话按钮
