### ISSUE TITLE
there is something wrong with BCE embedding and I have already arise PR to fix , please review

### ISSUE THREAD

**Issue by Yazooliu** [netease-youdao/QAnything#39]
in https://github.com/netease-youdao/BCEmbedding/pull/6
I found the inference code of BCE  embedding model using transformer is NOT correct .
I had update code to fix this issue.
please review my PR and it's easy to approve.

BestRegards
Yazhou

**Comment by shenlei1020** [comment]
Thanks! Your PR has been merged into BCEmbedding repository: https://github.com/netease-youdao/BCEmbedding

**Comment by Yazooliu** [comment]
> Thanks! Your PR has been merged into BCEmbedding repository: https://github.com/netease-youdao/BCEmbedding

yes, I see it. 
I also working on RAG/embedding/reranker and also see your code.
let's keep in talk.


BR
Yazhou from Hundsun
