### ISSUE TITLE
[BUG] 拉取镜像时qanything_local这个文件下载不下来，进度条的第5位置下载不下来

### ISSUE THREAD

**Issue by huweibin1983** [netease-youdao/QAnything#40]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

拉取镜像时qanything_local这个文件下载不下来，进度条的第5和13位置下载不下来。
试过很多次到最后就是进度条卡着不动了。

### 期望行为 | Expected Behavior

希望能正常拉取镜像

### 运行环境 | Environment

```Markdown
- OS:Windows11
- NVIDIA Driver:546.33
- CUDA:12.3.52
- Docker Compose:Docker Desktop 4.26.1
- NVIDIA GPU Memory:24G
```

**Comment by huweibin1983** [comment]
![屏幕截图 2024-01-19 164100](https://github.com/netease-youdao/QAnything/assets/84638487/d912202e-4df7-46ca-88ce-2cd39ee6a382)
画圈那一格进度条到最后卡死下载不下来。

**Comment by xixihahaliu** [comment]
> ![屏幕截图 2024-01-19 164100](https://private-user-images.githubusercontent.com/84638487/298004425-d912202e-4df7-46ca-88ce-2cd39ee6a382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjI3NjIsIm5iZiI6MTcwNTY2MjQ2MiwicGF0aCI6Ii84NDYzODQ4Ny8yOTgwMDQ0MjUtZDkxMjIwMmUtNGRmNy00NmNhLTg4Y2UtMmNkMzllZTZhMzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDExMDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMzZlOTMwZGY3MTI1MzVhYTI4NTc0NmMyMjU0NWFlZWQ1YmFmOWZhNGIwN2Q5MmQ2MmFhNzdmY2U5MTI1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.05fhqBPmY36zIedsPP3W3-5BYh9LaUBcsULsV_KZeO8) 画圈那一格进度条到最后卡死下载不下来。

可能是网络问题，可以尝试一下手动docker pull freeren/qanything-win:v1.0.9 这个镜像，或者去Docker Desktop中手动搜索并下载

**Comment by huweibin1983** [comment]
网络的问题，后面找了一个软件加速才下下来。

**Comment by Theviro1** [comment]
这个位置不拉行么
