### ISSUE TITLE
请问有计划支持Qwen之外的LLM模型吗？

### ISSUE THREAD

**Issue by thiner** [netease-youdao/QAnything#41]
我搜索了代码，看起来现在是在代码中hard code了使用Qwen的模型进行内容生成。请问有计划支持别的模型吗？或者支持以接口调用的形式集成其它LLM推理服务吗？

**Comment by successren** [comment]
Support for custom LLM is one of our most important next steps and should be available soon, welcome to watch

**Comment by RonaldJEN** [comment]
有计划直接接入外部api嘛

**Comment by CopyNinja1999** [comment]
> Support for custom LLM is one of our most important next steps and should be available soon, welcome to watch

Do you have plan to support API-based LLM like GPT? Notice that there is a file named run_for_online while no option to deploy with it.

**Comment by songkq** [comment]
@CopyNinja1999 @thiner @RonaldJEN 
QAnything-v1.2.0 supports OpenAI API and a public LLM as a LLM service. 
<img width="936" alt="image" src="https://github.com/netease-youdao/QAnything/assets/30183023/dd6e5579-e00e-474d-a218-115e6c8bd513">

For more information, please refer to https://github.com/netease-youdao/QAnything/releases and https://github.com/netease-youdao/QAnything/blob/master/docs/QAnything_Startup_Usage_README.md.
