### ISSUE TITLE
[BUG] Error in Powerful PDF parsing: max() arg is an empty sequence

### ISSUE THREAD

**Issue by xeon-ye** [netease-youdao/QAnything#414]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

LOCAL DATA PATH: C:\home\QAnything\QANY_DB\content
LOCAL_RERANK_REPO: netease-youdao/bce-reranker-base_v1
LOCAL_EMBED_REPO: netease-youdao/bce-embedding-base_v1
table model initing...
cpu
table model inited...
2024-06-25 15:54:52,646 Start OCR！
2024-06-25 15:54:52,652 OCR finished in 2.090221200021915 seconds
WARNING:root:Miss outlines
23it [00:00, ?it/s]
preprocess
preprocess
23it [00:00, 22996.18it/s]
**2024-06-25 15:54:54,819 Error in Powerful PDF parsing: max() arg is an empty sequence**
2024-06-25 15:54:54,820 PDF Parse finished in 2.1685440000146627 seconds
C:/home/QAnything/example\test_md\test.md

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- docker:
- docker-compose:
- NVIDIA GPU:
- NVIDIA GPU Memory:
```

**Comment by ARSblithe212** [comment]
我也遇到了，请问你怎么解决的

**Comment by zhudongwork** [comment]
同样的问题，真的解决了吗？

**Comment by yangy996** [comment]
同样的问题，解决了吗

**Comment by 18612852541** [comment]
+1 请问怎么解决的
