### ISSUE TITLE
[BUG] error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

### ISSUE THREAD

**Issue by liwenju0** [netease-youdao/QAnything#42]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

登录到远程服务器，下载最新的项目代码。
执行bash run.sh
models 文件夹已存在，无需下载。
Checking model directories...
检查模型目录...
检查模型版本成功，当前版本为 v2.1.0。
Model directories check passed. (0/8)
模型路径和模型版本检查通过. (0/8)
Do you want to use the previous host: local? (yes/no) 是否使用上次的host: local？(yes/no) 回车默认选yes，请输入:no
Are you running the code on a cloud server or on your local machine? (cloud/local) 您是在云服务器上还是本地机器上启动代码？(cloud/local) cloud
Please enter the server IP address 请输入服务器IP地址(示例：10.234.10.144): 172.20.1.17
Running under native Linux
[+] Running 0/0
 ⠋ standalone Pulling                                                                                                                               0.0s 
 ⠋ minio Pulling                                                                                                                                    0.0s 
 ⠋ qanything_local Pulling                                                                                                                          0.0s 
 ⠋ mysql Pulling                                                                                                                                    0.0s 
 ⠋ etcd Pulling                                                                                                                                     0.0s 
error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`
(base) deepctrl@dell:~/liwenju/QAnything$ bash run.sh
models 文件夹已存在，无需下载。
Checking model directories...
检查模型目录...
检查模型版本成功，当前版本为 v2.1.0。
Model directories check passed. (0/8)
模型路径和模型版本检查通过. (0/8)
Do you want to use the previous host: 172.20.1.17? (yes/no) 是否使用上次的host: 172.20.1.17？(yes/no) 回车默认选yes，请输入:no
Are you running the code on a cloud server or on your local machine? (cloud/local) 您是在云服务器上还是本地机器上启动代码？(cloud/local) local
Running under native Linux
[+] Running 0/0
 ⠋ mysql Pulling                                                                                                                                    0.0s 
 ⠋ standalone Pulling                                                                                                                               0.0s 
 ⠋ minio Pulling                                                                                                                                    0.0s 
 ⠋ etcd Pulling                                                                                                                                     0.0s 
 ⠋ qanything_local Pulling                                                                                                                          0.0s 
error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`
(base) deepctrl@dell:~/liwenju/QAnything$ bash run.sh
models 文件夹已存在，无需下载。
Checking model directories...
检查模型目录...
检查模型版本成功，当前版本为 v2.1.0。
Model directories check passed. (0/8)
模型路径和模型版本检查通过. (0/8)
Do you want to use the previous host: localhost? (yes/no) 是否使用上次的host: localhost？(yes/no) 回车默认选yes，请输入:no
Are you running the code on a cloud server or on your local machine? (cloud/local) 您是在云服务器上还是本地机器上启动代码？(cloud/local) cloud
Please enter the server IP address 请输入服务器IP地址(示例：10.234.10.144): 172.20.1.17
Running under native Linux
[+] Running 0/0
 ⠋ mysql Pulling                                                                                                                                     0.0s 
 ⠋ qanything_local Pulling                                                                                                                           0.0s 
 ⠋ minio Pulling                                                                                                                                     0.0s 
 ⠋ standalone Pulling                                                                                                                                0.0s 
 ⠋ etcd Pulling                                                                                                                                      0.0s 
error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

尝试了cloud 和local两种选择，都报这个错误。

### 期望行为 | Expected Behavior

正常启动

### 运行环境 | Environment

```Markdown
- OS:Linux version 4.15.0-213-generic (buildd@lcy02-amd64-079) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023
- NVIDIA Driver:535.129.03
- CUDA:  cuda_12.1.r12.1
- Docker Compose:2.24.1
- NVIDIA GPU Memory: 80G
```

### QAnything日志 | QAnything logs

没有产生 api.log

**Comment by liwenju0** [comment]
sudo apt install gnome-keyring
安装后解决

**Comment by liuyijiang1994** [comment]
我也报这个错，不过是：
