### ISSUE TITLE
最新的版本V1.4.1没有发布docker image吗？

### ISSUE THREAD

**Issue by tiansf85** [netease-youdao/QAnything#424]
在hub.docker.com上面只有三个月前发布的1.2.2版本image,没有最新的image吗？

**Comment by zhangever** [comment]
同问

**Comment by xixihahaliu** [comment]
@tiansf85 @zhangever 最新的v1.4.1只有纯python版本，不依赖docker镜像，docker镜像的1.2.2版本对应的是最新的docker版本（master分支），因此1.2.2就是最新的镜像了，只有docker版需要用到。另外下周将发布v2.0版本，docker和python版本合二为一了
