### ISSUE TITLE
python版本与master版本的问题

### ISSUE THREAD

**Issue by tusm123** [netease-youdao/QAnything#426]
python分支，没有支持milvus的写入；这个原因是啥？我能否直接把master分支的milvus_client copy过来使用，并且加上配置信息

**Comment by fi5ee** [comment]
同问

**Comment by zhangever** [comment]
同问， 感觉怪怪的。 docker版本又只有一个3个月之前的v1.2.2版本， 跟当前的v1.4.1差距很大

**Comment by xixihahaliu** [comment]
@tusm123 @fi5ee @zhangever 因为纯python环境无法使用milvus，使用milvus必须搭配milvus的docker镜像（milvus-lite可以在纯python下跑通，QAnything的1.3.0版本里有用到，但是lite库bug太多且官方不维护了，1.4.0就放弃了），下周将会发布v2.0版本，docker版本和python版本合二为一了。
