### ISSUE TITLE
请问使用问答接口的时候history如何自动获取，手动调用问答接口没有history信息

### ISSUE THREAD

**Issue by xinxin12345** [netease-youdao/QAnything#427]
**Please Describe The Problem To Be Solved**
(Replace This Text: Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope.)

**(Optional): Suggest A Solution**
(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by ManjunXiong** [comment]
我也发现了这个问题，目前我想的解决方法是，请求问答接口时，将history添加进去

**Comment by xixihahaliu** [comment]
@xinxin12345 @ManjunXiong 简单说就是把上次问答的结果主动传给问答接口的history，因为api调用都是one-time的，没办法自动获取history，手动记录手动传入就行了，history示例：[[“问题1”， “回答1”]，["问题2"]，“回答2”]

**Comment by ManjunXiong** [comment]
> @xinxin12345 @ManjunXiong 简单说就是把上次问答的结果主动传给问答接口的history，因为api调用都是one-time的，没办法自动获取history，手动记录手动传入就行了，history示例：[[“问题1”， “回答1”]，["问题2"]，“回答2”]

谢谢
