### ISSUE TITLE
直接利用已有的向量结果进行rerank以改善 CPU 推理的性能

### ISSUE THREAD

**Issue by kbaicai** [netease-youdao/QAnything#439]
我尝试在 docker 容器上用 cpu 跑的时候，发现 cpu 的推理瓶颈主要在 rerank 模块，rerank的性能消耗应该也大部分是 encode，为啥不考虑直接利用已有的向量呢？

**Comment by linhuifj** [comment]
rerank是cross encoder结构的，query和candidate共同进入网络做计算。query和candidate都不同，无法利用已有的向量。
embedding是利用已有向量做比较。

**Comment by kbaicai** [comment]
谢谢你的解释，我明白了！另外，我还想请教一下，如果把 rerank 相关的服务独立出来，有没有推荐的云服务可以满足需求？非常感谢！
