### ISSUE TITLE
windows上使用pychorm开发调试选择哪个分支呢

### ISSUE THREAD

**Issue by xuelikanmeihua** [netease-youdao/QAnything#440]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- docker:
- docker-compose:
- NVIDIA GPU:
- NVIDIA GPU Memory:
```

**Comment by xixihahaliu** [comment]
可以选择qanything-python分支

**Comment by xuelikanmeihua** [comment]
没有使用windows wls，启动时是报错的

**Comment by xuelikanmeihua** [comment]
没有使用windows WSL，启动时是报错的
