### ISSUE TITLE
前端代码什么时候开源呢

### ISSUE THREAD

**Issue by ForeseeBear** [netease-youdao/QAnything#479]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

代码中前端代码是打包后的

### 期望行为 | Expected Behavior

希望将前端代码一起开源

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- docker:
- docker-compose:
- NVIDIA GPU:
- NVIDIA GPU Memory:
```

**Comment by ForeseeBear** [comment]
找到了

**Comment by thus10** [comment]
> 找到了

你好 前端是混淆后的代码，如何二开呢？

**Comment by Xtaiyang** [comment]
在哪呀

**Comment by feria-tu** [comment]
> 找到了

请问在哪有啊
