### ISSUE TITLE
v2源码部署教程

### ISSUE THREAD

**Issue by lix8886** [netease-youdao/QAnything#490]
现在只有docker, 从源码安装部署教程呢？

**Comment by Vastzhang97** [comment]
同催更~~谢谢！

**Comment by netease-youdao** [comment]
目前由于依赖milvus和es，这两个库无法在纯python下运行，所以没有源码安装部署教程，如果不使用es，并把milvus手动改回faiss，那才能不依赖docker，这里是镜像的Dockerfile，可以参考下，https://github.com/netease-youdao/QAnything/blob/qanything-v2/build_images/Dockerfile， @LixiangHello @Vastzhang97
