### ISSUE TITLE
还是希望出一个 GPU 版本……

### ISSUE THREAD

**Issue by bigbrother666sh** [netease-youdao/QAnything#538]
主要是 CPU 版本太占内存啦……
32G 内存的机器硬是吃掉了90%，swap 100%，吓得我赶忙把 swap扩大到24G

但是类似16G 内存+1080 GPU这样的电脑很多啊，这岂不是运行目前版本很尴尬……

另外，我也很怀疑 i5这种 cpu 执行 embedding 和 rerank 的效率……

**Comment by gjfmlj** [comment]
强烈希望

**Comment by EchoWht** [comment]
如果使用使用GPU来进行embedding 和 rerank 的，效果和效率是不是会更佳？

**Comment by bigbrother666sh** [comment]
我浅薄了，仔细研究后发现，对于混合检索系统，没啥必要上 GPU……

**Comment by zifengdexiatian** [comment]
> 检索

能请教一下为什么吗？为什么没必要上GPU。

**Comment by bigbrother666sh** [comment]
因为最慢的又不是向量搜索那一步……上了 GPU 不也得等

**Comment by bigbrother666sh** [comment]
况且 onnx框架本身就是为 cpu 优化的

**Comment by zifengdexiatian** [comment]
> 况且 onnx框架本身就是为 cpu 优化的

原来如此，感谢
