### ISSUE TITLE
2.0更新了，之前的1.41版本还能部署使用吗，我看这两个版本的部署文档git克隆命令都是一样的，有没有大佬知道

### ISSUE THREAD

**Issue by JefreeCN** [netease-youdao/QAnything#543]
**Please Describe The Problem To Be Solved**
(Replace This Text: Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope.)

**(Optional): Suggest A Solution**
(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by GUILTYxC** [comment]
checkout一下master分支就可以了吧
