### ISSUE TITLE
[BUG] <title>部署好之后，11434端口根本就没有启动，一提问就报错：connect error

### ISSUE THREAD

**Issue by Adminsmh** [netease-youdao/QAnything#554]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

部署好之后，11434端口根本就没有启动，一提问就报错：connect error

### 期望行为 | Expected Behavior

部署好之后，11434端口根本就没有启动，一提问就报错：connect error

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

### QAnything日志 | QAnything logs

部署好之后，11434端口根本就没有启动，一提问就报错：connect error

### 复现方法 | Steps To Reproduce

部署好之后，11434端口根本就没有启动，一提问就报错：connect error

### 备注 | Anything else?

部署好之后，11434端口根本就没有启动，一提问就报错：connect error

**Comment by xixihahaliu** [comment]
11434端口是ollama大模型服务默认占用的端口，我们的服务并不会替您自动安装ollama和部署ollama大模型服务，需要您手动安装和启动ollama大模型服务后11434端口将被占用，使用ollama方式详见官网：https://ollama.com/
