### ISSUE TITLE
如何加载其他qwen模型

### ISSUE THREAD

**Issue by takemars** [netease-youdao/QAnything#63]
**Please Describe The Problem To Be Solved**
目前加载的模型文件为：
![image](https://github.com/netease-youdao/QAnything/assets/101978375/560e9caa-d6ea-4448-bb3a-8dcd87e08534)
请问如何将原始的qwen模型转换为这种格式，能提供相应的脚本和说明吗？
**(Optional): Suggest A Solution**
(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by huliangbing** [comment]
同问

**Comment by wxz1996** [comment]
+1

**Comment by rookiexiao123** [comment]
同问，如何加载其他llm？

**Comment by songkq** [comment]
First, you should check the `/path/to/QAnything/third_party/FastChat/fastchat/conversation.py` to confirm whether the conversation template of LLM has been supported by FastChat. If not, you should add your `conv_template`. After that, you can load public LLM models following this way by using huggingface transformers or vllm backend. 

<img width="946" alt="image" src="https://github.com/netease-youdao/QAnything/assets/30183023/2fd6faf7-3cdc-4c0c-af6c-174868565fbb">
<img width="961" alt="image" src="https://github.com/netease-youdao/QAnything/assets/30183023/8d609ab1-8ab9-400f-a0d8-a2f879674e75">


https://github.com/netease-youdao/QAnything/blob/master/docs/QAnything_Startup_Usage_README.md
