### ISSUE TITLE
可以单独部署微调后的qwen模型吗

### ISSUE THREAD

**Issue by sssuperrrr** [netease-youdao/QAnything#82]
没有找到加载微调qwen模型的代码

**Comment by 315930399** [comment]
顺便问下，默认使用FasterTransformer作为base模型的推理后端，可以切换为VLLM吗？

**Comment by songkq** [comment]
@315930399 
```

## Step 1. Prepare the QAnything project and download local Embedding/Rerank models.

git clone https://github.com/netease-youdao/QAnything.git
cd /path/to/QAnything && mkdir -p tmp && cd tmp
git lfs install
git clone https://huggingface.co/netease-youdao/QAnything
unzip QAnything/models.zip
cd - && mv tmp/models .

## Step 2. Download the public LLM model (e.g., Qwen-7B-QAnything) and save to "/path/to/QAnything/assets/custom_models"
cd /path/to/QAnything/assets/custom_models
git clone https://huggingface.co/netease-youdao/Qwen-7B-QAnything

## Step 3. Execute the service startup command.  Here we use "-b vllm" to specify the Huggingface transformers backend.
## Here we use "-b vllm" to specify the vllm backend that will do bf16 inference as default.
## Note you should adjust the gpu_memory_utilization yourself according to the model size to avoid out of memory (e.g., gpu_memory_utilization=0.81 is set default for 7B. Here, gpu_memory_utilization is set to 0.85 by "-r 0.85").
cd /path/to/QAnything
bash ./run.sh -c local -i 0 -b vllm -m Qwen-7B-QAnything -t qwen-7b-qanything -p 1 -r 0.85
```


@sssuperrrr  
```
mkdir -p /workspace/qanything_local/logs/debug_logs/fastchat_logs && cd /workspace/qanything_local/logs/debug_logs/fastchat_logs

nohup python3 -m fastchat.serve.controller --host 0.0.0.0 --port 7800 > /workspace/qanything_local/logs/debug_logs/fastchat_logs/fschat_controller_7800.log 2>&1 &

nohup python3 -m fastchat.serve.openai_api_server --host 0.0.0.0 --port 7802 --controller-address http://0.0.0.0:7800 > /workspace/qanything_local/logs/debug_logs/fastchat_logs/fschat_openai_api_server_7802.log 2>&1 &

export LLM_API_SERVE_CONV_TEMPLATE="qwen-7b-qanything"
export LLM_API_SERVE_MODEL="Qwen-7B-QAnything"
CUDA_VISIBLE_DEVICES="0" nohup python3 -m fastchat.serve.model_worker --host 0.0.0.0 --port 7801 \
            --controller-address http://0.0.0.0:7800 --worker-address http://0.0.0.0:7801 \
            --model-path /model_repos/CustomLLM/$LLM_API_SERVE_MODEL --load-8bit \
            --dtype bfloat16 --conv-template $LLM_API_SERVE_CONV_TEMPLATE > /workspace/qanything_local/logs/debug_logs/fastchat_logs/fschat_model_worker_7801.log 2>&1 &

https://github.com/netease-youdao/QAnything/blob/3f4a74dedc2eb8279be810d81ab25871b76f0b26/scripts/run_for_local_option.sh#L165

```

**Comment by sssuperrrr** [comment]
I got it, thanks!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "netease-youdao/QAnything"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [netease-youdao/QAnything] 可以单独部署微调后的qwen模型吗 (Issue #82)





 
@315930399
  ## Step 1. Prepare the QAnything project and download local Embedding/Rerank models. git clone https://github.com/netease-youdao/QAnything.git cd /path/to/QAnything &amp;&amp; mkdir -p tmp &amp;&amp; cd tmp git lfs install git clone https://huggingface.co/netease-youdao/QAnything unzip QAnything/models.zip cd - &amp;&amp; mv tmp/models . ## Step 2. Download the public LLM model (e.g., Qwen-7B-QAnything) and save to "/path/to/QAnything/assets/custom_models" cd /path/to/QAnything/assets/custom_models git clone https://huggingface.co/netease-youdao/Qwen-7B-QAnything ## Step 3. Execute the service startup command.  Here we use "-b vllm" to specify the Huggingface transformers backend. ## Here we use "-b vllm" to specify the vllm backend that will do bf16 inference as default. ## Note you should adjust the gpu_memory_utilization yourself according to the model size to avoid out of memory (e.g., gpu_memory_utilization=0.81 is set default for 7B. Here, gpu_memory_utilization is set to 0.85 by "-r 0.85"). cd /path/to/QAnything bash ./run.sh -c local -i 0 -b vllm -m Qwen-7B-QAnything -t qwen-7b-qanything -p 1 -r 0.85  
@sssuperrrr
 mkdir -p /workspace/qanything_local/logs/debug_logs/fastchat_logs &amp;&amp; cd /workspace/qanything_local/logs/debug_logs/fastchat_logs nohup python3 -m fastchat.serve.controller --host 0.0.0.0 --port 7800 &gt; /workspace/qanything_local/logs/debug_logs/fastchat_logs/fschat_controller_7800.log 2&gt;&amp;1 &amp; nohup python3 -m fastchat.serve.openai_api_server --host 0.0.0.0 --port 7802 --controller-address http://0.0.0.0:7800 &gt; /workspace/qanything_local/logs/debug_logs/fastchat_logs/fschat_openai_api_server_7802.log 2&gt;&amp;1 &amp; export LLM_API_SERVE_CONV_TEMPLATE="qwen-7b-qanything" export LLM_API_SERVE_MODEL="Qwen-7B-QAnything" CUDA_VISIBLE_DEVICES="0" nohup python3 -m fastchat.serve.model_worker --host 0.0.0.0 --port 7801 \             --controller-address http://0.0.0.0:7800 --worker-address http://0.0.0.0:7801 \             --model-path /model_repos/CustomLLM/$LLM_API_SERVE_MODEL --load-8bit \             --dtype bfloat16 --conv-template $LLM_API_SERVE_CONV_TEMPLATE &gt; /workspace/qanything_local/logs/debug_logs/fastchat_logs/fschat_model_worker_7801.log 2&gt;&amp;1 &amp; https://github.com/netease-youdao/QAnything/blob/3f4a74dedc2eb8279be810d81ab25871b76f0b26/scripts/run_for_local_option.sh#L165

**Comment by tianyumyum** [comment]
@songkq 您好请问自定义的llm是在什么阶段发生作用呢，是chat的部分还是两阶段（即embedding和reranker）中作用呢？
