### ISSUE TITLE
自定义文本分割器的疑问

### ISSUE THREAD

**Issue by Daya-Jin** [netease-youdao/QAnything#83]
我看代码里对于docx格式用的是自定义的ChineseTextSplitter，我就在本地试了下对于docx文档的分割效果，这个分类器把一个word切的很细碎，单个文本切片基本不会超过一句话的长度

但是我在网页上上传同一个word文档去提问，检索出来的数据来源就很长，一大段好几百字，而且还是连续的，感觉像用的是langchain默认的RecursiveCharacterTextSplitter

是不是网页产品跟开源代码使用的分割器有差异，还是配置差异？有大佬解答下不

**Comment by successren** [comment]
The implementation of the text splitter is as follows:
1. split the text at the sentence level.
2. Embedding each segmented sentence;
3. Search for some of the most relevant sentences according to the query, which is called kernel sentence here;
4. Put together the related context sentences of these kernel sentences to form a large paragraph;
5. Large paragraphs go into the subsequent rerank model.

It's similar to langchain parent document retriever, please refer to  https://python.langchain.com/docs/modules/data_connection/retrievers/parent_document_retriever

**Comment by Daya-Jin** [comment]
看到了，感谢

**Comment by rxy1212** [comment]
@Daya-Jin 相关代码在哪个文件里？我看了很久源码没找到哦

**Comment by rxy1212** [comment]
@successren 大佬 我看源码里的处理是把句子切分后存向量，检索的时候也是检索短的句子，只是把相同 file_id 且相邻 chunk_id 的结果合并 这样貌似很难达到网页上很长的相关文本的效果，这中间还有什么操作吗？

**Comment by newbietuan** [comment]
> @Daya-Jin 相关代码在哪个文件里？我看了很久源码没找到哦

大佬，找到了吗
